name: laravel_echo_null
description: This Package is the improved version of the original package "laravel_echo", with some modifications and features.
version: 0.0.8+4
homepage: https://github.com/AIabdoPr/laravel_echo_null.git

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  pinenacl: ^0.6.0
  pusher_client_socket: ^0.0.2+4
  socket_io_client: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: null
