name: laravel_echo_null
description: This Package is the improved version of the original package "laravel_echo", with some modifications and features.
version: 0.0.5+3
homepage: https://github.com/AIabdoPr/laravel_echo_null.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  # dart_pusher_channels: ^1.1.0
  flutter:
    sdk: flutter
  pusher_client_fixed: ^0.0.2
  socket_io_client: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: null
