name: laravel_echo_null
description: This Package is the improved version of the original package "laravel_echo", with some modifications and features.
version: 0.0.7
homepage: https://github.com/AIabdoPr/laravel_echo_null.git

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pusher_client_socket: ^0.0.1+1
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: null
